[project]
name = "pysparkdt"
version = "0" # DO NOT CHANGE - managed by Git tags and CI
description = "An open-source Python library for simplifying local testing of Databricks workflows that use PySpark and Delta tables."
authors = [{ name = "Juraj Pall", email = "juraj.pall@datamole.ai" }]
readme = "README.md"
requires-python = ">=3.10, <3.15"
license = { text = "MIT" }
dependencies = [
    "pyspark[sql]>=4.0.0,<4.1.0",
    "delta-spark>=3.0.0,<4.1.0",
    "numpy>=1.26.0",
    "pandas<3.0.0",  # PySpark 4.0.x not compatible with Pandas 3.0.x (30.1.2026) + Python 3.10 not compatible with Pandas 3
    "setuptools>=75.6.0,<76.0.0; python_version >= '3.12'",  # Necessary for Python 3.12+ as distutils is missing without it
]

[project.urls]
repository = "https://github.com/datamole-ai/pysparkdt"

[dependency-groups]
dev = [
    "ruff>=0.14.14,<0.15.0",
    "pytest>=9.0.2,<10.0.0",
    "pytest-mock>=3.15.1,<4.0.0",
]

[tool.ruff]
line-length = 79
target-version = "py310"
lint.select = [
    "E",
    "F",
    "N",
    "W",
    "I001",
]

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402", "F401"]
"*/**" = ["E402"]

[tool.pytest.ini_options]
testpaths = ["tests"]
norecursedirs = ["example"]
pythonpath = ["."]

[build-system]
requires = ["uv-build>=0.11.25,<0.12"]
build-backend = "uv_build"
